'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';

const Card=({children,className=''}:{children:React.ReactNode;className?:string})=><div className={`card ${className}`}>{children}</div>;
const Tag=({children,orange=false}:{children:React.ReactNode;orange?:boolean})=><span className={`tag ${orange?'tag-orange':''}`}>{children}</span>;
const SectionTitle=({number,eyebrow,title}:{number:string;eyebrow:string;title:string})=><div className="section-title"><span className="section-number">{number}</span><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div>;
function DataTable({rows,three=false}:{rows:string[][];three?:boolean}){return <div className="table-wrap"><table><thead><tr><th>Dimensión</th><th>P5</th>{three&&<th>P50</th>}<th>P95</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]}>{row.map((cell,i)=>i===0?<th scope="row" key={cell}>{cell}</th>:<td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div>}

export default function Home(){
 const[progress,setProgress]=useState(0);const[deskHeight,setDeskHeight]=useState(52);
 useEffect(()=>{const update=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setProgress(max>0?Math.round(window.scrollY/max*100):0)};update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);
 return <div>
  <header className="topbar"><div className="nav-shell"><a className="brand" href="#portada"><span>P5</span><b>Antropometría · Ergonomía</b></a><nav aria-label="Navegación principal"><a href="#ej1">01 Estación</a><a href="#ej2">02 Pupitre</a><a href="#ej3">03 Cargas</a><a href="#conclusiones">Conclusiones</a></nav></div><div className="progress"><span style={{width:`${progress}%`}}/></div></header>
  <section id="portada" className="hero grid-bg"><div className="shell hero-grid"><div><p className="eyebrow">Ficha técnica · Práctica académica</p><h1>Práctica de <em>Antropometría</em></h1><p className="lead">Diseño ergonómico para percentiles 5.º–95.º</p><div className="tags"><Tag>Materia: Ergonomía</Tag><Tag orange>3 ejercicios</Tag></div><div className="identity-grid">{['Alumnos|Emmanuel Alejandro Juárez Del Río · Regina Rocha Gonzalez','Docente|Nombre del docente','Grupo|Grupo','Fecha|dd / mm / aaaa'].map(item=>{const[label,value]=item.split('|');return <div key={label}><small>{label}</small><strong>{value}</strong></div>})}</div><div className="jump-list"><a href="#ej1">01 · Estación de trabajo sentada <span>→</span></a><a href="#ej2">02 · Pupitre eléctrico infantil <span>→</span></a><a href="#ej3">03 · Puesto para manejo de cargas <span>→</span></a></div></div><Card className="intro-card"><p className="eyebrow">Introducción</p><p>Diseñar para los percentiles 5.º al 95.º permite adaptar un producto aproximadamente al <strong>90 % de la población</strong>, excluyendo únicamente los extremos antropométricos.</p><div className="bell" aria-label="Distribución entre los percentiles 5 y 95"><span>P5</span><div><i>90 % de la población</i></div><span>P95</span></div><p className="note">El producto se adapta a la persona; la persona no debe forzar su postura para adaptarse al producto.</p></Card></div></section>
  <div className="status"><div className="shell"><span>AVANCE</span><div><i style={{width:`${progress}%`}}/></div><b>{progress}%</b></div></div>
  <main className="shell main-content">
   <section id="ej1"><SectionTitle number="01" eyebrow="Ejercicio 1" title="Estación de trabajo sentada"/><div className="two-col"><Card><p className="label">Datos antropométricos</p><p className="caption">Medidas en centímetros · percentiles 5.º y 95.º</p><DataTable rows={[["Altura poplítea","38 cm","47 cm"],["Altura del codo sentado","22 cm","30 cm"],["Longitud del muslo","40 cm","50 cm"]]}/></Card><Card className="image-card"><p className="label">Esquema técnico · vista lateral</p><Image src="/images/ejercicio-1-estacion-sentada.jpg" alt="Persona sentada correctamente en una estación ajustable" width={1536} height={1024}/></Card></div><p className="subheading">Cálculos paso a paso</p><div className="three-col"><Card className="calc"><b>01 · Altura del asiento</b><p>Se toma la altura poplítea de la población objetivo.</p><code>38–47 cm</code><small>Diseño ajustable sugerido: 38–48 cm.</small></Card><Card className="calc"><b>02 · Altura de mesa</b><p>P5: 38 + 22 = 60 cm<br/>P95: 47 + 30 = 77 cm</p><code>60–77 cm</code><small>Mesa ajustable sugerida: 62–78 cm.</small></Card><Card className="calc"><b>03 · Profundidad</b><p>P5: 40 − 3 = 37 cm<br/>P95: 50 − 5 = 45 cm</p><code>37–45 cm</code><small>Debe dejar espacio detrás de la rodilla.</small></Card></div></section>
   <section id="ej2"><SectionTitle number="02" eyebrow="Ejercicio 2" title="Pupitre eléctrico infantil"/><div className="two-col"><Card><p className="label">Datos · niños de 6 a 8 años</p><DataTable rows={[["Estatura total","108 cm","132 cm"],["Altura poplítea","30 cm","38 cm"],["Codo sentado","15 cm","22 cm"],["Longitud del muslo","30 cm","38 cm"],["Antebrazo","18 cm","23 cm"]]}/></Card><Card className="image-card"><p className="label">Propuesta · regulación eléctrica</p><Image src="/images/ejercicio-2-pupitre-electrico.jpg" alt="Pupitre infantil eléctrico con asiento y tablero ajustables" width={1536} height={1024}/></Card></div><Card className="control-card"><div><p className="label">Simulador de altura del tablero</p><h3>{deskHeight} cm</h3><p>Rango eléctrico recomendado: 45–60 cm</p></div><input aria-label="Altura del tablero en centímetros" type="range" min="45" max="60" value={deskHeight} onChange={e=>setDeskHeight(Number(e.target.value))}/><div className="range-labels"><span>45 cm · P5</span><span>60 cm · P95</span></div></Card><div className="three-col"><Card className="calc"><b>Asiento</b><code>30–38 cm</code><small>Ajuste basado en la altura poplítea.</small></Card><Card className="calc"><b>Tablero</b><p>30 + 15 = 45 cm<br/>38 + 22 = 60 cm</p><code>45–60 cm</code></Card><Card className="calc"><b>Profundidad</b><p>30 − 3 = 27 cm<br/>38 − 5 = 33 cm</p><code>27–33 cm</code></Card></div><div className="feature-grid">{['Motor silencioso','Botones grandes ↑ ↓','Indicador de altura','Bloqueo infantil','Sensor antipellizco','Protección antivuelco','Bordes redondeados','Canaleta para cables','Tablero inclinable'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div><p className="footnote"><b>Respaldo:</b> se recomienda una regulación aproximada de 25–35 cm desde el asiento y soporte lumbar. Es una recomendación de diseño, no un cálculo exacto, porque la práctica no proporciona la altura del tronco ni de los hombros.</p></section>
   <section id="ej3"><SectionTitle number="03" eyebrow="Ejercicio 3" title="Puesto para manejo de cargas"/><div className="metrics"><div><small>PESO</small><b>10 kg</b></div><div><small>FRECUENCIA</small><b>5/min</b></div><div><small>JORNADA</small><b>8 h</b></div><div><small>RECORRIDO ACTUAL</small><b>90 cm</b></div></div><div className="two-col"><Card><p className="label">Datos antropométricos</p><DataTable three rows={[["Codo de pie","90 cm","100 cm","110 cm"],["Alcance frontal","55 cm","65 cm","75 cm"],["Altura de rodilla","45 cm","50 cm","55 cm"]]}/></Card><Card><p className="label">Riesgos actuales</p><ul className="risk-list"><li>Flexión repetida del tronco al recoger desde 40 cm.</li><li>Elevación de brazos y hombros para depositar a 130 cm.</li><li>Giro del tronco si las superficies no están alineadas.</li><li>Fatiga acumulada y riesgo para espalda, hombros, cuello y muñecas.</li></ul></Card></div><Card className="wide-image"><p className="label">Comparación · antes y después</p><Image src="/images/ejercicio-3-manejo-cargas.jpg" alt="Comparación entre levantamiento inseguro y transferencia ergonómica" width={1680} height={941}/></Card><div className="before-after"><Card className="danger"><p className="label">Antes · puesto actual</p><h3>40 → 130 cm</h3><p>La diferencia vertical de 90 cm obliga a flexionar la espalda y elevar los hombros.</p></Card><Card className="success"><p className="label">Después · propuesta</p><h3>75–100 cm</h3><p>Mesa elevadora y cinta a alturas semejantes, con rodillos y carga próxima al cuerpo.</p></Card></div><p className="subheading">Criterios del rediseño</p><div className="criteria">{['Bandeja elevable entre 75 y 100 cm.','Cinta ajustable aproximadamente entre 80 y 100 cm.','Carga y herramientas frecuentes a 35–45 cm del cuerpo.','Alcance máximo de 55 cm, tomando como referencia al P5.','Bandeja y cinta alineadas para evitar torsiones.','Rodillos o asistencia mecánica para disminuir el levantamiento.','Controles dentro del alcance cómodo.','Espacio inferior libre para pies y rodillas.','Rotación de tareas y pausas de recuperación.'].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div><p className="footnote"><b>Nota:</b> no se calcula un índice NIOSH exacto porque faltan la distancia horizontal real, el recorrido vertical detallado, la asimetría, el tipo de agarre y el patrón de pausas.</p></section>
   <section id="conclusiones"><SectionTitle number="✓" eyebrow="Síntesis" title="Conclusiones"/><div className="conclusion-grid"><Card><b>Diseño ajustable</b><p>Es la estrategia más efectiva para atender del percentil 5 al 95.</p></Card><Card><b>Posturas neutrales</b><p>Reduce flexión, estiramiento y elevación excesiva de las articulaciones.</p></Card><Card><b>Adaptación real</b><p>El producto se adapta al usuario y mejora seguridad, comodidad y desempeño.</p></Card></div></section>
   <section id="fuentes" className="method"><p className="eyebrow">Fuente y nota metodológica</p><p>Los cálculos parten de los datos antropométricos incluidos en la práctica académica. Los rangos obtenidos mediante operaciones se presentan como resultados; los mecanismos de seguridad, ajustes ampliados y medidas organizativas se identifican como recomendaciones. Las dimensiones que requieren altura de tronco, hombros, anchura de cadera o detalles del levantamiento necesitan información complementaria.</p></section>
  </main><footer><div className="shell"><span>Práctica de Antropometría Ergonómica</span><span>P5–P95 · 90 % de la población</span></div></footer>
 </div>
}
